// Generated from JSON node type description
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeType {
    ExclamationMark,
    DoubleQuote,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    SingleQuote,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    ArrowRight,
    Dot,
    Slash,
    Colon,
    Semicolon,
    LeftAngle,
    Equal,
    RightAngle,
    Question,
    QuestionRight,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    DoubleRightBracketGreater,
    Caret,
    Underscore,
    Backtick,
    AtxH1Marker,
    AtxH2Marker,
    AtxH3Marker,
    AtxH4Marker,
    AtxH5Marker,
    AtxH6Marker,
    AtxHeading,
    BackslashEscape,
    BlockContinuation,
    BlockQuote,
    BlockQuoteMarker,
    CodeFenceContent,
    Document,
    EntityReference,
    FencedCodeBlock,
    FencedCodeBlockDelimiter,
    HtmlBlock,
    IndentedCodeBlock,
    InfoString,
    Inline,
    Language,
    LinkDestination,
    LinkLabel,
    LinkReferenceDefinition,
    LinkTitle,
    List,
    ListItem,
    ListMarkerDot,
    ListMarkerMinus,
    ListMarkerParenthesis,
    ListMarkerPlus,
    ListMarkerStar,
    MinusMetadata,
    NumericCharacterReference,
    Paragraph,
    PipeTable,
    PipeTableAlignLeft,
    PipeTableAlignRight,
    PipeTableCell,
    PipeTableDelimiterCell,
    PipeTableDelimiterRow,
    PipeTableHeader,
    PipeTableRow,
    PlusMetadata,
    Section,
    SetextH1Underline,
    SetextH2Underline,
    SetextHeading,
    TaskListMarkerChecked,
    TaskListMarkerUnchecked,
    ThematicBreak,
    LeftCurly,
    AbsoluteValue,
    RightCurly,
    Tilde,
}

impl NodeType {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "!" => Some(NodeType::ExclamationMark),
            "\"" => Some(NodeType::DoubleQuote),
            "#" => Some(NodeType::Hash),
            "$" => Some(NodeType::Dollar),
            "%" => Some(NodeType::Percent),
            "&" => Some(NodeType::Ampersand),
            "'" => Some(NodeType::SingleQuote),
            "(" => Some(NodeType::LeftParen),
            ")" => Some(NodeType::RightParen),
            "*" => Some(NodeType::Asterisk),
            "+" => Some(NodeType::Plus),
            "," => Some(NodeType::Comma),
            "-" => Some(NodeType::Minus),
            "-->" => Some(NodeType::ArrowRight),
            "." => Some(NodeType::Dot),
            "/" => Some(NodeType::Slash),
            ":" => Some(NodeType::Colon),
            ";" => Some(NodeType::Semicolon),
            "<" => Some(NodeType::LeftAngle),
            "=" => Some(NodeType::Equal),
            ">" => Some(NodeType::RightAngle),
            "?" => Some(NodeType::Question),
            "?>" => Some(NodeType::QuestionRight),
            "@" => Some(NodeType::At),
            "[" => Some(NodeType::LeftBracket),
            "\\" => Some(NodeType::Backslash),
            "]" => Some(NodeType::RightBracket),
            "]]>" => Some(NodeType::DoubleRightBracketGreater),
            "^" => Some(NodeType::Caret),
            "_" => Some(NodeType::Underscore),
            "`" => Some(NodeType::Backtick),
            "atx_h1_marker" => Some(NodeType::AtxH1Marker),
            "atx_h2_marker" => Some(NodeType::AtxH2Marker),
            "atx_h3_marker" => Some(NodeType::AtxH3Marker),
            "atx_h4_marker" => Some(NodeType::AtxH4Marker),
            "atx_h5_marker" => Some(NodeType::AtxH5Marker),
            "atx_h6_marker" => Some(NodeType::AtxH6Marker),
            "atx_heading" => Some(NodeType::AtxHeading),
            "backslash_escape" => Some(NodeType::BackslashEscape),
            "block_continuation" => Some(NodeType::BlockContinuation),
            "block_quote" => Some(NodeType::BlockQuote),
            "block_quote_marker" => Some(NodeType::BlockQuoteMarker),
            "code_fence_content" => Some(NodeType::CodeFenceContent),
            "document" => Some(NodeType::Document),
            "entity_reference" => Some(NodeType::EntityReference),
            "fenced_code_block" => Some(NodeType::FencedCodeBlock),
            "fenced_code_block_delimiter" => Some(NodeType::FencedCodeBlockDelimiter),
            "html_block" => Some(NodeType::HtmlBlock),
            "indented_code_block" => Some(NodeType::IndentedCodeBlock),
            "info_string" => Some(NodeType::InfoString),
            "inline" => Some(NodeType::Inline),
            "language" => Some(NodeType::Language),
            "link_destination" => Some(NodeType::LinkDestination),
            "link_label" => Some(NodeType::LinkLabel),
            "link_reference_definition" => Some(NodeType::LinkReferenceDefinition),
            "link_title" => Some(NodeType::LinkTitle),
            "list" => Some(NodeType::List),
            "list_item" => Some(NodeType::ListItem),
            "list_marker_dot" => Some(NodeType::ListMarkerDot),
            "list_marker_minus" => Some(NodeType::ListMarkerMinus),
            "list_marker_parenthesis" => Some(NodeType::ListMarkerParenthesis),
            "list_marker_plus" => Some(NodeType::ListMarkerPlus),
            "list_marker_star" => Some(NodeType::ListMarkerStar),
            "minus_metadata" => Some(NodeType::MinusMetadata),
            "numeric_character_reference" => Some(NodeType::NumericCharacterReference),
            "paragraph" => Some(NodeType::Paragraph),
            "pipe_table" => Some(NodeType::PipeTable),
            "pipe_table_align_left" => Some(NodeType::PipeTableAlignLeft),
            "pipe_table_align_right" => Some(NodeType::PipeTableAlignRight),
            "pipe_table_cell" => Some(NodeType::PipeTableCell),
            "pipe_table_delimiter_cell" => Some(NodeType::PipeTableDelimiterCell),
            "pipe_table_delimiter_row" => Some(NodeType::PipeTableDelimiterRow),
            "pipe_table_header" => Some(NodeType::PipeTableHeader),
            "pipe_table_row" => Some(NodeType::PipeTableRow),
            "plus_metadata" => Some(NodeType::PlusMetadata),
            "section" => Some(NodeType::Section),
            "setext_h1_underline" => Some(NodeType::SetextH1Underline),
            "setext_h2_underline" => Some(NodeType::SetextH2Underline),
            "setext_heading" => Some(NodeType::SetextHeading),
            "task_list_marker_checked" => Some(NodeType::TaskListMarkerChecked),
            "task_list_marker_unchecked" => Some(NodeType::TaskListMarkerUnchecked),
            "thematic_break" => Some(NodeType::ThematicBreak),
            "{" => Some(NodeType::LeftCurly),
            "|" => Some(NodeType::AbsoluteValue),
            "}" => Some(NodeType::RightCurly),
            "~" => Some(NodeType::Tilde),
            _ => None,
        }
    }
}
impl NodeType {
    pub fn as_str(&self) -> &'static str {
        match self {
            NodeType::ExclamationMark => "!",
            NodeType::DoubleQuote => "\"",
            NodeType::Hash => "#",
            NodeType::Dollar => "$",
            NodeType::Percent => "%",
            NodeType::Ampersand => "&",
            NodeType::SingleQuote => "'",
            NodeType::LeftParen => "(",
            NodeType::RightParen => ")",
            NodeType::Asterisk => "*",
            NodeType::Plus => "+",
            NodeType::Comma => ",",
            NodeType::Minus => "-",
            NodeType::ArrowRight => "-->",
            NodeType::Dot => ".",
            NodeType::Slash => "/",
            NodeType::Colon => ":",
            NodeType::Semicolon => ";",
            NodeType::LeftAngle => "<",
            NodeType::Equal => "=",
            NodeType::RightAngle => ">",
            NodeType::Question => "?",
            NodeType::QuestionRight => "?>",
            NodeType::At => "@",
            NodeType::LeftBracket => "[",
            NodeType::Backslash => "\\",
            NodeType::RightBracket => "]",
            NodeType::DoubleRightBracketGreater => "]]>",
            NodeType::Caret => "^",
            NodeType::Underscore => "_",
            NodeType::Backtick => "`",
            NodeType::AtxH1Marker => "atx_h1_marker",
            NodeType::AtxH2Marker => "atx_h2_marker",
            NodeType::AtxH3Marker => "atx_h3_marker",
            NodeType::AtxH4Marker => "atx_h4_marker",
            NodeType::AtxH5Marker => "atx_h5_marker",
            NodeType::AtxH6Marker => "atx_h6_marker",
            NodeType::AtxHeading => "atx_heading",
            NodeType::BackslashEscape => "backslash_escape",
            NodeType::BlockContinuation => "block_continuation",
            NodeType::BlockQuote => "block_quote",
            NodeType::BlockQuoteMarker => "block_quote_marker",
            NodeType::CodeFenceContent => "code_fence_content",
            NodeType::Document => "document",
            NodeType::EntityReference => "entity_reference",
            NodeType::FencedCodeBlock => "fenced_code_block",
            NodeType::FencedCodeBlockDelimiter => "fenced_code_block_delimiter",
            NodeType::HtmlBlock => "html_block",
            NodeType::IndentedCodeBlock => "indented_code_block",
            NodeType::InfoString => "info_string",
            NodeType::Inline => "inline",
            NodeType::Language => "language",
            NodeType::LinkDestination => "link_destination",
            NodeType::LinkLabel => "link_label",
            NodeType::LinkReferenceDefinition => "link_reference_definition",
            NodeType::LinkTitle => "link_title",
            NodeType::List => "list",
            NodeType::ListItem => "list_item",
            NodeType::ListMarkerDot => "list_marker_dot",
            NodeType::ListMarkerMinus => "list_marker_minus",
            NodeType::ListMarkerParenthesis => "list_marker_parenthesis",
            NodeType::ListMarkerPlus => "list_marker_plus",
            NodeType::ListMarkerStar => "list_marker_star",
            NodeType::MinusMetadata => "minus_metadata",
            NodeType::NumericCharacterReference => "numeric_character_reference",
            NodeType::Paragraph => "paragraph",
            NodeType::PipeTable => "pipe_table",
            NodeType::PipeTableAlignLeft => "pipe_table_align_left",
            NodeType::PipeTableAlignRight => "pipe_table_align_right",
            NodeType::PipeTableCell => "pipe_table_cell",
            NodeType::PipeTableDelimiterCell => "pipe_table_delimiter_cell",
            NodeType::PipeTableDelimiterRow => "pipe_table_delimiter_row",
            NodeType::PipeTableHeader => "pipe_table_header",
            NodeType::PipeTableRow => "pipe_table_row",
            NodeType::PlusMetadata => "plus_metadata",
            NodeType::Section => "section",
            NodeType::SetextH1Underline => "setext_h1_underline",
            NodeType::SetextH2Underline => "setext_h2_underline",
            NodeType::SetextHeading => "setext_heading",
            NodeType::TaskListMarkerChecked => "task_list_marker_checked",
            NodeType::TaskListMarkerUnchecked => "task_list_marker_unchecked",
            NodeType::ThematicBreak => "thematic_break",
            NodeType::LeftCurly => "{",
            NodeType::AbsoluteValue => "|",
            NodeType::RightCurly => "}",
            NodeType::Tilde => "~",
        }
    }
}
